---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudtty
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://release.daocloud.io/chartrepo/cloudtty
